// This file is generated by scripts/updateProjectRepos.js.
// Do not edit by hand.

export const PROJECTS_GENERATED = [
    {
        repo: 'AdventOfCode',
    },
    {
        repo: 'AdventOfCode2019',
    },
    {
        repo: 'AdventOfCode2021',
    },
    {
        repo: 'AIffinity',
    },
    {
        repo: 'angular-playground',
    },
    {
        repo: 'AppAlling',
    },
    {
        repo: 'asa-backups',
    },
    {
        repo: 'AuthorizationServer',
    },
    {
        repo: 'AutoClerk',
    },
    {
        repo: 'az-bacpac-blob-mssql-importer',
    },
    {
        repo: 'AzBlobDownloader',
    },
    {
        repo: 'Database-Containerizer',
    },
    {
        repo: 'DotnetExecutor',
    },
    {
        repo: 'E3Ultra-Klipper',
    },
    {
        repo: 'EfCorePublicIdDemo',
    },
    {
        repo: 'ExperimentFramework',
    },
    {
        repo: 'ExpirableCollections',
    },
    {
        repo: 'FolderProcessor',
    },
    {
        repo: 'Jdh.Home',
    },
    {
        repo: 'jerrettdavis.github.io',
    },
    {
        repo: 'MillProbeStudio',
    },
    {
        repo: 'MyQDotNet',
    },
    {
        repo: 'nitrado-api-extractor',
    },
    {
        repo: 'Notes',
    },
    {
        repo: 'OmmaLicenseValidator',
    },
    {
        repo: 'PatternKit',
    },
    {
        repo: 'PhysicalFileProviderTests',
    },
    {
        repo: 'PkceChallenge',
    },
    {
        repo: 'PowerShell.Modules',
    },
    {
        repo: 'RedditResponderBot',
    },
    {
        repo: 'secret-share',
    },
    {
        repo: 'SemanticKernel.Plugins.Tests',
    },
    {
        repo: 'Slncs',
    },
    {
        repo: 'StrataConfig',
    },
    {
        repo: 'TaskDSL',
    },
    {
        repo: 'Voron24-Klipper',
    },
    {
        repo: 'WebApiCatchAll',
    },
];
